services:
  app:
    container_name: bibacell_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '7812:7812'
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    depends_on:
      - db
    env_file:
      - ./backend/.env
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:14
    restart: always
    ports:
      - '6543:6543'
    environment:
      POSTGRES_USER: nehoroshiyparen
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: BIBACELL
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  node_modules: