services:
  app:
    container_name: bibacell_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - '7812:7812'
    volumes:
      - ./backend:/app:cached
      - node_modules_app:/app/node_modules
      - ./uploads:/app/uploads
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USERNAME=nehoroshiyparen
      - DB_PASSWORD=1212
      - DB_NAME=BIBACELL
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads/final:/usr/share/nginx/uploads/final:ro
    ports:
      - "8080:80"
    restart: unless-stopped

  client:
    container_name: bibacell_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev  # или Dockerfile.prod, если prod
    ports:
      - "9973:9973"  # порт для фронтенда
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - app
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:14
    restart: always
    ports:
      - '6543:5432'
    environment:
      POSTGRES_USER: nehoroshiyparen
      POSTGRES_PASSWORD: 1212
      POSTGRES_DB: BIBACELL
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:latest  # или конкретная версия, например redis:7.2
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data  # сохраняем данные Redis между перезапусками
    restart: unless-stopped  # автоматический перезапуск
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.0.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      
  kibana:
    image: docker.elastic.co/kibana/kibana:9.0.3
    container_name: kibana
    environment:
    - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    - SERVER_SSL_ENABLED=false
    - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    - CSP_STRICT=false
    - XPACK_SECURITY_ENABLED=false
    ports:
      - "5601:5601"

volumes:
  pgdata:
  node_modules:
  redis_data:
  node_modules_app:
  es_data: