FROM node:22

WORKDIR /app

RUN apt-get update && apt-get install -y graphicsmagick ghostscript

# Копируем только манифесты
COPY package*.json ./
COPY patches ./patches

# Чистая установка всех зависимостей под Linux
RUN npm ci

# Копируем остальной код
COPY . .

EXPOSE 7812

# dev-скрипт с esbuild
CMD ["npm", "run", "dev"]