FROM node:22

WORKDIR /app

# Копируем только манифесты
COPY package*.json ./

# Чистая установка всех зависимостей под Linux
RUN npm ci

# Копируем остальной код
COPY . .

EXPOSE 7812

# dev-скрипт с esbuild
CMD ["npm", "run", "dev"]